export type PostStatus = "draft" | "scheduled" | "published";
export type Post = { id:number; title:string; slug:string; excerpt:string; body:string; category:string; tags:string[]; status:PostStatus; publishedAt:string; scheduledAt:string | null; readingMinutes:number; visual:string; };

export const seedPosts: Post[] = [
  { id:1, title:"퇴직 후 첫 30일, 돈보다 먼저 정리할 7가지", slug:"first-30-days-after-retirement", excerpt:"통장, 보험, 실업급여부터 생활 리듬까지. 불안을 줄이는 첫 달 체크리스트입니다.", body:"퇴직 직후에는 새로운 일을 급하게 찾기보다, 지금 가진 시간과 돈을 정확히 파악하는 일이 먼저입니다.\n\n첫째, 고정지출을 생존·유지·선택의 세 단계로 나눕니다. 둘째, 퇴직금과 비상금을 생활비 계좌와 분리합니다. 셋째, 실업급여 신청 가능 여부와 일정을 확인합니다.\n\n## 1. 한 달 생활비를 다시 계산하세요\n\n회사에 다닐 때의 지출과 퇴직 후 지출은 다릅니다. 교통비와 점심값은 줄지만 건강보험료처럼 새로 체감되는 비용이 생깁니다. 최근 3개월 카드와 이체 내역을 기준으로 최소 생활비를 계산하세요.\n\n## 2. 중요한 날짜를 달력에 표시하세요\n\n실업급여, 건강보험, 연금 관련 일정은 놓치면 다시 처리하기 번거롭습니다. 공식 기관 안내를 확인하고 신청일과 준비물을 한 장에 정리하세요.", category:"퇴직 준비", tags:["퇴직 체크리스트","생활비","실업급여"], status:"published", publishedAt:"2026-08-08", scheduledAt:null, readingMinutes:6, visual:"30D" },
  { id:2, title:"실업급여 받으며 가능한 부업, 어디까지일까?", slug:"side-jobs-while-receiving-benefits", excerpt:"소득 신고가 필요한 경우와 취업으로 보는 기준을 공식 안내 중심으로 정리했습니다.", body:"실업급여를 받는 동안 부업을 시작할 수 있지만, 근로 사실과 소득은 반드시 정확하게 신고해야 합니다. 플랫폼 수익이나 단기 아르바이트도 예외로 생각하지 않는 편이 안전합니다.\n\n## 공식 기준을 먼저 확인하세요\n\n개인마다 근로 시간과 계약 형태가 다르므로 고용24와 관할 고용센터에서 본인 상황을 확인해야 합니다. 인터넷의 경험담은 참고만 하고, 신청 전에는 공식 답변을 기록해 두세요.\n\n## 작은 수익도 기록하세요\n\n입금일, 금액, 일을 한 날짜와 시간을 표로 남기면 실업인정일에 당황하지 않습니다. 이 기록은 나중에 부업의 실제 시간당 수익을 계산하는 자료로도 쓸 수 있습니다.", category:"정부지원·실업급여", tags:["실업급여","부업","소득신고"], status:"published", publishedAt:"2026-08-05", scheduledAt:null, readingMinutes:7, visual:"Q&A" },
  { id:3, title:"AI로 블로그 글 한 편 쓰는 시간을 3시간 줄였습니다", slug:"ai-blog-writing-workflow", excerpt:"자료 수집부터 초안, 사실 확인, 발행까지 직접 시험한 현실적인 작업 순서입니다.", body:"AI에게 제목 하나만 주고 글 전체를 맡기면 그럴듯하지만 비슷한 글이 나옵니다. 시간을 줄이려면 사람과 AI가 맡을 일을 분리해야 합니다.\n\n## 자료는 사람이 고릅니다\n\n정부 정책과 금융 정보는 공식 출처를 먼저 모읍니다. AI는 자료를 찾는 도구가 아니라, 선택한 자료를 비교하고 초안 구조를 잡는 도구로 사용합니다.\n\n## 발행 전 세 가지를 확인합니다\n\n숫자와 날짜, 신청 조건, 출처 링크를 사람이 다시 확인합니다. 마지막으로 자신의 경험이나 판단을 더해야 읽을 이유가 있는 글이 됩니다.", category:"AI 활용", tags:["AI 글쓰기","블로그","자동화"], status:"published", publishedAt:"2026-08-02", scheduledAt:null, readingMinutes:5, visual:"−3H" },
];

export function slugify(value:string){ return value.trim().toLowerCase().replace(/[^a-z0-9가-힣]+/g,"-").replace(/^-|-$/g,""); }
