import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { InnerHeader, SiteFooter } from "../../../components/SiteChrome";
import { liveKeywordPages } from "../../../../lib/portal";

type Props={params:Promise<{region:string;topic:string}>};
export async function generateStaticParams(){return liveKeywordPages.map(item=>({region:encodeURIComponent(item.region),topic:encodeURIComponent(item.topic)}));}
function safeDecode(value:string){try{return decodeURIComponent(value);}catch{return value;}}
function findPage(region:string,topic:string){const r=safeDecode(region);const t=safeDecode(topic);return liveKeywordPages.find(item=>item.region===r&&item.topic===t);}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {region,topic}=await params;const page=findPage(region,topic);return page?{title:page.label,description:`${page.label}를 찾을 때 먼저 확인할 전국·지역 공식 창구와 신청 조건을 정리합니다.`,alternates:{canonical:`/local/${region}/${topic}`},robots:{index:false,follow:true}}:{};}
export default async function LocalPage({params}:Props){const {region,topic}=await params;const page=findPage(region,topic);if(!page)notFound();const regionName=safeDecode(region);const path=`/local/${region}/${topic}`;return <><InnerHeader path={path} eyebrow="LOCAL PRACTICAL GUIDE" title={page.label} description={`${regionName}에서 일자리와 지원 정보를 찾을 때 헤매지 않도록 확인 순서를 정리했습니다.`}/><main className="content-shell article-copy policy-copy"><h2>전국 서비스에서 먼저 내 조건을 좁혀보세요</h2><p>고용24에서 지역, 희망 직종과 훈련 유형을 선택하고 정부24·복지로에서 나이와 가구 조건에 맞는 지원을 확인합니다. 검색 결과의 사업명과 담당기관을 메모하면 지역 문의가 쉬워집니다.</p><h2>{regionName}에서 확인할 세 가지</h2><ol><li>시·구·군 홈페이지에서 ‘중장년’, ‘일자리’, ‘평생교육’을 각각 검색합니다.</li><li>관할 고용복지플러스센터와 중장년내일센터의 상담 대상과 예약 방법을 확인합니다.</li><li>마음에 드는 사업은 접수일·거주지·소득·중복수급 조건을 한 줄에 적습니다.</li></ol><div className="policy-links"><a href="https://www.work24.go.kr/" target="_blank" rel="noreferrer">고용24에서 일자리 찾기 ↗</a><a href="https://www.gov.kr/" target="_blank" rel="noreferrer">정부24에서 지원 찾기 ↗</a></div><h2>전화하기 전에 준비하면 좋은 질문</h2><p>“{regionName} 거주자이며 현재 고용 상태는 ○○입니다. 신청 가능한 사업과 다음 모집일이 있나요?”처럼 거주지, 나이대, 고용 상태와 원하는 도움을 함께 말해보세요. 상담 내용과 담당기관 이름을 기록하면 같은 설명을 반복하는 시간을 줄일 수 있습니다.</p></main><SiteFooter/></>}
